networks:
  zabbix-net:
    name: zabbix-net
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "${BACKEND_ENABLE_IPV6}"
    internal: true
    ipam:
      driver: "${BACKEND_NETWORK_DRIVER}"
      config:
        - subnet: "${BACKEND_SUBNET}"

services:
  postgres-server:
    container_name: zabbix-postgres-server
    image: "${POSTGRESQL_IMAGE}:${POSTGRESQL_IMAGE_TAG}"
    #  command: -c ssl=on -c ssl_cert_file=/run/secrets/server-cert.pem -c ssl_key_file=/run/secrets/server-key.pem -c ssl_ca_file=/run/secrets/root-ca.pem
    ports:
      - "5432:5432"
    restart: "${RESTART_POLICY}"
    volumes:
      - ${DATA_DIRECTORY}/var/lib/postgresql/data:/var/lib/postgresql/data:rw
      - ${ENV_VARS_DIRECTORY}/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
      - ${ENV_VARS_DIRECTORY}/.ZBX_DB_CERT_FILE:/run/secrets/server-cert.pem:ro
      - ${ENV_VARS_DIRECTORY}/.ZBX_DB_KEY_FILE:/run/secrets/server-key.pem:ro
    env_file:
      - ${ENV_VARS_DIRECTORY}/.env_db_pgsql
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    stop_grace_period: 1m
    networks:
      zabbix-net:
        aliases:
          - postgres-server

  zabbix-server:
    container_name: zabbix-zabbix-server
    init: true
    image: "${ZABBIX_SERVER_PGSQL_IMAGE}:${ZABBIX_ALPINE_IMAGE_TAG}${ZABBIX_IMAGE_TAG_POSTFIX}"
    # ports:
    #   - "${ZABBIX_SERVER_PORT}:10051"
    restart: "${RESTART_POLICY}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIRECTORY}/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - ${DATA_DIRECTORY}/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ${DATA_DIRECTORY}/var/lib/zabbix/dbscripts:/var/lib/zabbix/dbscripts:ro
      - ${DATA_DIRECTORY}/var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - ${DATA_DIRECTORY}/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ${DATA_DIRECTORY}/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ${DATA_DIRECTORY}/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ${DATA_DIRECTORY}/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      # - snmptraps:/var/lib/zabbix/snmptraps:ro
      # - ${ENV_VARS_DIRECTORY}/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
      # - ${ENV_VARS_DIRECTORY}/.ZBX_DB_CERT_FILE:/run/secrets/server-cert.pem:ro
      # - ${ENV_VARS_DIRECTORY}/.ZBX_DB_KEY_FILE:/run/secrets/server-key.pem:ro
    depends_on:
      - postgres-server
    env_file:
      - ${ENV_VARS_DIRECTORY}/.env_db_pgsql
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      zabbix-net:
        aliases:
          - zabbix-server

  zabbix-agent:
    container_name: zabbix-zabbix-agent
    init: true
    image: "${ZABBIX_AGENT_IMAGE}:${ZABBIX_ALPINE_IMAGE_TAG}${ZABBIX_IMAGE_TAG_POSTFIX}"
    # ports:
    #   - "${ZABBIX_AGENT_PORT}:10050"
    restart: "${RESTART_POLICY}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIRECTORY}/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      - ${DATA_DIRECTORY}/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ${DATA_DIRECTORY}/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ${DATA_DIRECTORY}/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    depends_on:
      - postgres-server
    env_file:
      - ${ENV_VARS_DIRECTORY}/.env_agent
    privileged: true
    networks:
      zabbix-net:
        aliases:
          - zabbix-agent

  zabbix-web:
    container_name: zabbix-zabbix-web
    image: "${ZABBIX_WEB_NGINX_PGSQL_IMAGE}:${ZABBIX_ALPINE_IMAGE_TAG}${ZABBIX_IMAGE_TAG_POSTFIX}"
    ports:
      - "${ZABBIX_WEB_NGINX_HTTP_PORT}:8080"
      - "${ZABBIX_WEB_NGINX_HTTPS_PORT}:8443"
    restart: "${RESTART_POLICY}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIRECTORY}/etc/ssl/nginx:/etc/ssl/nginx:ro
      - ${DATA_DIRECTORY}/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
    depends_on:
      - postgres-server
      - zabbix-server
      - zabbix-agent
    env_file:
      - ${ENV_VARS_DIRECTORY}/.env_db_pgsql
      - ${ENV_VARS_DIRECTORY}/.env_web
    # healthcheck:
    #   test: [ "CMD", "curl", "-f", "http://localhost:8080/ping" ]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 30s
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      zabbix-net:
        aliases:
          - zabbix-web

secrets:
  POSTGRES_USER:
    file: ${ENV_VARS_DIRECTORY}/.POSTGRES_USER
  POSTGRES_PASSWORD:
    file: ${ENV_VARS_DIRECTORY}/.POSTGRES_PASSWORD
